<?php

namespace frontend\controllers;
use common\models\BriTokens;
use common\models\Events;
use common\models\EventType;
use common\models\EventsAndRoles;
use common\models\Tokens;
use common\models\User;
use common\models\UserRank;
use Yii;
use yii\base\Event;

class MainController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest){
            $this->redirect('/site/login');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex($selRankId = null)
    {
        /* @var $user User*/
        $user = Yii::$app->user->identity;
        if (!$selRankId){
            UserRank::setRank($user);
            $selRankId = $user->rank_id;
        }
        $selRank = UserRank::findOne($selRankId);

        $rankList = UserRank::find()->all();
        $events = Events::find()->all();
        $userEvents = Events::getUserEvents($user);
        return $this->render('index', [
            'user' => $user,
            'selRank' => $selRank,
            'rankList' => $rankList,
            'events' => $events,
            'userEvents' => $userEvents,
        ]);
    }

    public function actionEvents($id = null){
        $user = Yii::$app->user->identity;
        $events = Events::find()->all();
        $eventType = EventType::find()->all();
        $userEvents = Events::getUserEvents($user);

        if(!$id){
            return $this->render('events',
            [
                'user' => $user,
                'events' => $events,
                'eventType' => $eventType,
                'userEvents' => $userEvents,
            ]
            );
        }else{
            return $this->render('event',
                [
                    'user' => $user,
                    'events' => $events,
                    'eventType' => $eventType,
                    'userEvents' => $userEvents,

                ]
            );
        }
    }

    /**
     * @return string
     */
    public function actionDocs(){
        return $this->render('docs', []);
    }

}
