<?php

namespace frontend\controllers;
use common\models\Actions;
use common\models\ActionTypes;
use common\models\Referals;
use common\models\UserRank;
use common\models\UsersSearchFront;
use common\models\User;
use Yii;
class SystemController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest){
            $this->redirect('/site/login');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionStatistic(){
        $user = Yii::$app->user->identity;
        $nextrank = UserRank::find()->where(['id'=>($user['rank_id']+1)])->one();
        $rank = UserRank::find()->where(['id'=>$user['rank_id']])->one();
        $actionTypes = ActionTypes::findOne(['id'=>7]);
        $actions = Actions::find()->where(['user_id'=>$user['id']])->andWhere(['type'=>7])->sum('sum');
        return $this->render('statistic', [
            'user'=>$user,
            'nextrank'=>$nextrank,
            'rank'=>$rank,
            'actiontypes'=>$actionTypes,
            'actions'=>$actions,
        ]);
    }

    /**
     * @return string
     */
    public function actionMembers($username = null){
        $user = Yii::$app->user->identity;
        $is_child = false;
        if(!empty($username)){
            $child = User::find()->where(['username'=>$username])->one();
            if(!empty($child)){
                $refs = Referals::find()->where(['user_id'=>$child['id'],'parent_id'=>$user['id']])->all();
                if(!empty($refs)){
                    $user = $child;
                    $is_child = true;
                }

            }
        }
        $searchModel = new UsersSearchFront();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('members', [
            'searchModel' => $searchModel,
            'user'=>$user,
            'dataProvider' => $dataProvider,
            'is_child' => $is_child,
        ]);
    }

}
