<?php

namespace frontend\controllers;

use common\models\User;
use common\models\UserRank;
use Yii;
use common\models\ActionTypes;
use common\models\Actions;

class SystemController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest){
            $this->redirect('/site/login');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionStatistic(){
        if(Yii::$app->user->isGuest){
            return $this->redirect('/site/login');
        }
        $user = Yii::$app->user->identity;
        $nextrank = UserRank::find()->where(['id'=>($user['rank_id']+1)])->one();
        $rank = UserRank::find()->where(['id'=>$user['rank_id']])->one();
        $actionTypes = ActionTypes::find()->all();
        $actions = Actions::find()->where(['user_id'=>$user['id']])->andWhere(['type'=>7])->sum('sum');
        return $this->render('statistic', [
            'user'=>$user,
            'nextrank'=>$nextrank,
            'rank'=>$rank,
            'actionTypes'=>$actionTypes,
            'actions'=>$actions,
        ]);
    }

}
